In [1]:
import pandas as pd

In [2]:
df_ad = pd.read_csv('admission_source_lookup.csv')
df_ad

    admission_source_id                                        description
0                     1                                 Physician Referral
1                     2                                    Clinic Referral
2                     3                                       HMO Referral
3                     4                           Transfer from a hospital
4                     5     Transfer from a Skilled Nursing Facility (SNF)
5                     6         Transfer from another health care facility
6                     7                                     Emergency Room
7                     8                              Court/Law Enforcement
8                     9                                      Not Available
9                    10              Transfer from critial access hospital
10                   11                                    Normal Delivery
11                   12                                 Premature Delivery
12                   13                                          Sick Baby
13                   14                                   Extramural Birth
14                   15                                      Not Available
15                   17                                                NaN
16                   18           Transfer From Another Home Health Agency
17                   19             Readmission to Same Home Health Agency
18                   20                                         Not Mapped
19                   21                                    Unknown/Invalid
20                   22   Transfer from hospital inpt/same fac reslt in...
21                   23                          Born inside this hospital
22                   24                         Born outside this hospital
23                   25            Transfer from Ambulatory Surgery Center
24                   26                              Transfer from Hospice

In [7]:
df_ad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   admission_source_id  25 non-null     int64
 1   description          24 non-null     object
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [9]:
df_di = pd.read_csv('discharge_disposition_lookup.csv')
df_di

,discharge_disposition_id,description
0,1,Discharged to home
1,2,Discharged/transferred to another short term h...
2,3,Discharged/transferred to SNF
3,4,Discharged/transferred to ICF
4,5,Discharged/transferred to another type of inpa...
5,6,Discharged/transferred to home with home healt...
6,7,Left AMA
7,8,Discharged/transferred to home under care of H...
8,9,Admitted as an inpatient to this hospital
9,10,Neonate discharged to another hospital for neo...
10,11,Expired
11,12,Still patient or expected to return for outpat...
12,13,Hospice / home
13,14,Hospice / medical facility
14,15,Discharged/transferred within this institution...
15,16,Discharged/transferred/referred another instit...
16,17,Discharged/transferred/referred to this instit...
17,18,NaN
18,19,"Expired at home. Medicaid only, hospice."
19,20,"Expired in a medical facility. Medicaid only, ..."
20,21,"Expired, place unknown. Medicaid only, hospice."
21,22,Discharged/transferred to another rehab fac in...
22,23,Discharged/transferred to a long term care hos...
23,24,Discharged/transferred to a nursing facility c...
24,25,Not Mapped
25,26,Unknown/Invalid
26,30,Discharged/transferred to another Type of Heal...
27,27,Discharged/transferred to a federal health car...
28,28,Discharged/transferred/referred to a psychiatr...
29,29,Discharged/transferred to a Critical Access Ho...

In [10]:
df_di.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   discharge_disposition_id  30 non-null     int64
 1   description               29 non-null     object
dtypes: int64(1), object(1)
memory usage: 612.0+ bytes

In [11]:
df_ty = pd.read_csv('admission_type_lookup.csv')
df_ty

   admission_type_id    description
0                  1      Emergency
1                  2         Urgent
2                  3       Elective
3                  4        Newborn
4                  5  Not Available
5                  6            NaN
6                  7  Trauma Center
7                  8     Not Mapped

In [12]:
df_ty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   admission_type_id  8 non-null      int64
 1   description        7 non-null      object
dtypes: int64(1), object(1)
memory usage: 260.0+ bytes